### ISSUE TITLE
cannot import name 'NotRequired' from 'typing'

### ISSUE THREAD

**Issue by Karabush** [shner-elmo/TradingView-Screener#9]
Hi,
I have the error - cannot import name 'NotRequired' from 'typing'

**Comment by shner-elmo** [comment]
Hey, I think you are using a Python version smaller than 3.11, I will add a fix to make it work on all Python versions >= 3.8.

**Comment by Karabush** [comment]
Yes, it's Python 3.10, whould be great to have compatibility with it as Python 3.11 is still not yet compatible with other libraries and don't want to update to it, thanks!

**Comment by shner-elmo** [comment]
This issue is now fixed from version `tradingview-screener==2.3.1`.

I have extended support for this package from Python 3.9 (3.8 is too old for certain dependencies).
